### ISSUE TITLE
Provide Labels on Generation

### ISSUE THREAD

**Issue by piccoloser** [machspec/labelmaker3#17]
After generating labels, the program should be provided with the labels in one of two ways:
- [x] Prompt to open/download
- [x] Open file

I'm partial to opening the generated file in a new tab because it demonstrates immediate feedback and allows the user to double-check the result before downloading (or printing) anything. Ideally, they'd also be able to easily download the generated file from there.

**Comment by thanhhong1994** [comment]
I used `svelte-pdf` to open a pdf viewer. Some browsers have restriction on opening a pdf file on the new tab and `iframe`, so the `PDFViewer` of `svelte-pdf` should be a good choice. Please check it out at branch `generate-label`.

**Comment by piccoloser** [comment]
Sweet — I'll take a look!

**Comment by piccoloser** [comment]
@thanhhong1994 I made some minor style changes to the PDF viewer, can you take a look? If you like what you see, I think it's ready for a PR :)
