### ISSUE TITLE
Incrementing Serial Numbers with Alphanumeric characters issue

### ISSUE THREAD

**Issue by jacobfaucette** [machspec/labelmaker3#33]
When there is a serial number with at least one letter between two numbers, the increment option does not work. Having the letters before the numbers causes no issues when incrementing.

Example is "1x1"

**Comment by piccoloser** [comment]
I hadn't accounted for serial numbers with numeric elements before the incremental portion. Updated the regular expression to the following:
```regex
(.*[^\d])(\d+$)
```
This matches `prefix` as any amount of characters (numerical or not) followed by a single instance of any non-numerical character, then the rest (which must be numerical) will be assigned to `num`.

This bugfix is being included in the PR for #35
