### ISSUE TITLE
Option for Small labels

### ISSUE THREAD

**Issue by jacobfaucette** [machspec/labelmaker3#39]
Requires the following.

Part number
Revision
Job( If required by customer)

![image001](https://github.com/machspec/labelmaker3/assets/75268319/19b61b8f-4e3d-4ba3-bd92-adb134cd9c3b)
[SMALL GEN.docx](https://github.com/machspec/labelmaker3/files/15474636/SMALL.GEN.docx)

The formatting in the template doc is messed up because someone made an edit and saved over it. The distance between the first two labels is what should be used.

Best way i see this working is to have a size option that can be selected before the person prints the labels. If the text goes off the label then the person would need to reformat data as needed.

We need to know the following measurements in millimeters:

- Top Margin: The distance from the top of the page to the top of the first label
- Row Gap: The gap (if any) between the rows of labels
- Column Gap: The gap (if any) between the columns of labels

**Comment by jacobfaucette** [comment]
Height
12.70 mm
0 mm gap
 
Width
44.72 mm
8 mm gap
 
13.44 mm from top
7.29 from left side

**Comment by piccoloser** [comment]
**Rows:** 20  
**Columns:** 4
