### ISSUE TITLE
Interfacing with Python interpreter via PyO3

### ISSUE THREAD

**Issue by piccoloser** [machspec/labelmaker3#5]

**Comment by thanhhong1994** [comment]
I updated UI a little bit and added functions to generate label by reusing you python code with Rust. 

On UI, you can fill out the information on UI (not serial number, I've not done anything with serial numbers), then click `Print` button, a pdf file will be generated in the folder `pdf`.

You can check it out at `generate-label` branch.

**Comment by piccoloser** [comment]
Great work!
